variables:
  solid_url: https://github.com/WirVsVirus-SoliD/SoliD-devops
  app_rootdir: /opt/solid
  user: root 

trigger:
  branches:
     include:
     - master
  tags:
    include:
    - v*.*

stages:
  - stage: updateRepos 
    jobs:
    - deployment: VMDeploy
      displayName: update repos
      environment:
        name: SoliD
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                workingDirectory: $(app_rootdir)
                script: |
                  sudo chown -R $(user):$(user) $(app_rootdir)
                  git stash && git pull

