trigger:
  tags:
    include:
    - v*.*
jobs:
- deployment: VMDeploy
  displayName: web
  environment:
    name: SoliD
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
