trigger:
  tags:
    include:
    - v*.*
jobs:
- deployment: VMDeploy
  displayName: web
  environment:
    name: SoliD
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: /opt/solid/solid
            script: |
              echo my first deployment > test.txt
