version: '2'



services:


  backend:
    image: wirvsvirussolid/solid:backend-${BACKEND_BRANCH}
    environment:
      geocodeKey: ${BACKEND_GEOCODEKEY}
      keycloak.server.url: ${KEYCLOAK_SERVER_URL}
      keycloak.server.url: ${KEYCLOAK_SERVER_URL}
      keycloak-secret: ${BACKEND_KEYCLOAK_SECRET}
      keycloak.useradmin.login: ${KEYCLOAK_USERADMIN_LOGIN}
      keycloak.useradmin.passwd: ${KEYCLOAK_USERADMIN_PASSWD}
      LETSENCRYPT_HOST: ${BACKEND_VIRTUAL_HOST}
      pghost: ${BACKEND_PGHOST}
      pgport: ${BACKEND_PGPORT}
      pgpasswd: ${BACKEND_PGPASSWD}
      pguser: ${BACKEND_PGUSER}
      quarkus.mailer.password: ${BACKEND_MAILER_PASSWORD}
      VIRTUAL_HOST: ${BACKEND_VIRTUAL_HOST}
      VIRTUAL_PORT: ${BACKEND_PORT}
    depends_on:
      - backend-db
    expose:
      - ${BACKEND_PORT}
    networks:
      - nginx-proxy
      - backend
    restart: always

  backend-db:
    image: postgres
    environment:
      POSTGRES_DB: solid
      POSTGRES_USER: ${BACKEND_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_DB_POSTGRES_PASSWORD}
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

volumes:
  backend-db-data:

networks:
  backend:
  nginx-proxy:
    external: true
