version: '2'



services:



  #backend:
    #image: wirvsvirussolid/solid:latest
    #environment:
      #VIRTUAL_HOST: ${BACKEND_VIRTUAL_HOST}
      #LETSENCRYPT_HOST: ${BACKEND_VIRTUAL_HOST}
      #VIRTUAL_PORT: ${BACKEND_PORT}
      #pghost: ${BACKEND_PGHOST}
      #pgport: ${BACKEND_PGPORT}
      #pgpasswd: ${BACKEND_PGPASSWD}
      #pguser: ${BACKEND_PGUSER}
    #expose:
      #- 8080
    #depends_on:
      #- backend-db

  #backend-db:
    #image: postgres
    #environment:
      #POSTGRES_DB: solid
      #POSTGRES_USER: ${BACKEND_DB_POSTGRES_USER}
      #POSTGRES_PASSWORD: ${BACKEND_DB_POSTGRES_PASSWORD}
    #volumes:
      #- backend-db-data:/var/lib/postgresql/data



  keycloak-db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    environment:
      VIRTUAL_HOST: ${KEYCLOAK_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${KEYCLOAK_VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      DB_SCHEMA: public
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    expose:
      - 8080
    depends_on:
      - keycloak-db



volumes:
  keycloak-db-data:
  backend-db-data:

networks:
  default:
    external:
      name: nginx-proxy

