version: '2'



services:

  keycloak-db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
    networks:
      - keycloak
    restart: always
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    environment:
      VIRTUAL_HOST: ${KEYCLOAK_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${KEYCLOAK_VIRTUAL_HOST}
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      DB_SCHEMA: public
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - nginx-proxy
      - keycloak
    expose:
      - 8080
    depends_on:
      - keycloak-db
    restart: always



volumes:
  keycloak-db-data:

networks:
  keycloak:
  nginx-proxy:
    external: true
