version: "3"

services:
  wp:
    image: wordpress:latest
    environment:
      LETSENCRYPT_HOST: ${WORDPRESS_VIRTUAL_HOST}
      VIRTUAL_HOST: ${WORDPRESS_VIRTUAL_HOST}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME:-wordpress}"
      WORDPRESS_TABLE_PREFIX: "${DB_TABLE_PREFIX:-wp_}"
      WORDPRESS_DB_USER: "${DB_USER:-root}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD:-password}"
    expose:
      - 80
    ports:
      - 8080:80
    networks:
      - nginx-proxy
      - backend
    depends_on:
      - db
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp-data:/var/www/html # Full wordpress project

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wp
    networks:
      - backend
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp-data:/var/www/html

  db:
    image: mariadb:latest
    environment: &dbEnvironment
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-password}"
      MYSQL_USER: "${DB_USER:-root}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_DATABASE: "${DB_NAME:-wordpress}"
    networks:
      - backend
    restart: always
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      - db-date:/var/lib/mysql

  adminer:
    image: adminer
    environment: 
      <<: *dbEnvironment
      LETSENCRYPT_HOST: ${ADMINER_VIRTUAL_HOST}
      VIRTUAL_HOST: ${ADMINER_VIRTUAL_HOST}

    expose:
      - 8080
    networks:
      - backend
      - nginx-proxy
    restart: always

volumes:
  db-date:
  wp-data:

networks:
  backend:
  nginx-proxy:
    external: true
